### Get /
GET  http://localhost:5000




###
POST http://localhost:5000/auth/register
Content-Type:  application/json



{
    "username" : "Chinedu",
    "password" : "Okeke"
}



###
POST http://localhost:5000/auth/login
Content-Type:  application/json



{
    "username" : "Chinedu",
    "password" : "Okeke"
}



